yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

ignore:
  - vendor
  # there are some long shell and long URL in test.yaml
  # which is not good to wrap them
  - .github/workflows/test.yaml

rules:
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 2
  comments-indentation: enable
  document-start: disable
  empty-lines:
    max: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  truthy: disable
